# ==============================================================================
# Phase B0 — FAIR coherence: metadata set via the (flat) metadata API must
# actually reach the generated standard artifacts. Before the fix the emitters
# only read legacy nested `.meta_json` participant/project objects and ignored
# METADATA.json fields entirely.
# ==============================================================================

library(testthat)
library(reindeer)

test_that("flat database-level metadata reaches the rendered README", {
  withr::local_options(reindeer.auto_cmdi = FALSE)
  ae <- create_isolated_ae_corpus()
  add_metadata(ae, list(Funder = "CoherenceFunder"))

  outdir <- withr::local_tempdir()
  describe_corpus(ae, output_dir = outdir, force = TRUE, verbose = FALSE)

  readme <- paste(readLines(file.path(outdir, "README.md"), warn = FALSE),
                  collapse = "\n")
  expect_match(readme, "CoherenceFunder", fixed = TRUE)
})

test_that("participant metadata reaches the CMDI as a speaker count", {
  # The media-corpus profile carries a corpus-level speaker count
  # (NumberOfSpeakers), not per-speaker Age/Gender (those belong to a
  # media-session profile). Field-level values reach the README instead.
  withr::local_options(reindeer.auto_cmdi = FALSE)
  ae <- create_isolated_ae_corpus()
  add_metadata(ae, list(Age = 33, Gender = "Female"), session = "0000")

  outdir <- withr::local_tempdir()
  describe_corpus(ae, output_dir = outdir, force = TRUE, verbose = FALSE)

  cmdi <- list.files(outdir, pattern = "_cmdi\\.xml$", full.names = TRUE)
  expect_gt(length(cmdi), 0)
  doc <- xml2::read_xml(cmdi[[1]])
  cmdp <- "http://www.clarin.eu/cmd/1/profiles/clarin.eu:cr1:p_1387365569699"
  spk <- xml2::xml_text(xml2::xml_find_first(
    doc, "//cmdp:NumberOfSpeakers", ns = c(cmdp = cmdp)))
  expect_match(spk, "^[0-9]+$")
})

test_that("README stamps provenance (generator + state hash)", {
  withr::local_options(reindeer.auto_cmdi = FALSE)
  ae <- create_isolated_ae_corpus()
  outdir <- withr::local_tempdir()
  describe_corpus(ae, output_dir = outdir, force = TRUE, verbose = FALSE)

  readme <- paste(readLines(file.path(outdir, "README.md"), warn = FALSE),
                  collapse = "\n")
  expect_match(readme, "Generated by reindeer")
  expect_match(readme, "Metadata state:")
})

test_that("README lists recorded participant attribute fields", {
  withr::local_options(reindeer.auto_cmdi = FALSE)
  ae <- create_isolated_ae_corpus()
  add_metadata(ae, list(Age = 30, Gender = "Male", Education = "Tertiary"),
               session = "0000")
  outdir <- withr::local_tempdir()
  describe_corpus(ae, output_dir = outdir, force = TRUE, verbose = FALSE)

  readme <- paste(readLines(file.path(outdir, "README.md"), warn = FALSE),
                  collapse = "\n")
  expect_match(readme, "Attributes recorded:")
  expect_match(readme, "education")  # field names are lowercased
})

test_that("DataCite record carries a version (metadata-state hash)", {
  withr::local_options(reindeer.auto_cmdi = FALSE)
  ae <- create_isolated_ae_corpus()
  outdir <- withr::local_tempdir()
  describe_corpus(ae, output_dir = outdir, force = TRUE, verbose = FALSE)

  dc <- list.files(outdir, pattern = "datacite.*\\.json$", full.names = TRUE)
  expect_gt(length(dc), 0)
  j <- jsonlite::read_json(dc[[1]])
  expect_false(is.null(j$data$attributes$version))
})

test_that("participants are built from resolved metadata, not just legacy files", {
  ae <- create_isolated_ae_corpus()
  add_metadata(ae, list(Age = 40, Gender = "Male"), session = "0000")

  parts <- reindeer:::collect_participant_metadata(ae, verbose = FALSE)
  expect_gt(length(parts), 0)
  # lowercase keys, values preserved
  first <- parts[[1]]
  expect_true(!is.null(first$age) || !is.null(first$gender))
})
