// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_allAttributeNames_cpp
StringVector get_allAttributeNames_cpp(List levelDefinitions);
RcppExport SEXP _reindeer_get_allAttributeNames_cpp(SEXP levelDefinitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type levelDefinitions(levelDefinitionsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_allAttributeNames_cpp(levelDefinitions));
    return rcpp_result_gen;
END_RCPP
}
// get_linkLevelChildrenNames_cpp
CharacterVector get_linkLevelChildrenNames_cpp(List linkDefinitions, std::string superlevelName);
RcppExport SEXP _reindeer_get_linkLevelChildrenNames_cpp(SEXP linkDefinitionsSEXP, SEXP superlevelNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type linkDefinitions(linkDefinitionsSEXP);
    Rcpp::traits::input_parameter< std::string >::type superlevelName(superlevelNameSEXP);
    rcpp_result_gen = Rcpp::wrap(get_linkLevelChildrenNames_cpp(linkDefinitions, superlevelName));
    return rcpp_result_gen;
END_RCPP
}
// expand_linkPath_cpp
List expand_linkPath_cpp(StringVector path);
RcppExport SEXP _reindeer_expand_linkPath_cpp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_linkPath_cpp(path));
    return rcpp_result_gen;
END_RCPP
}
// build_sublevelPathes_cpp
List build_sublevelPathes_cpp(List DBconfig, std::string levelName);
RcppExport SEXP _reindeer_build_sublevelPathes_cpp(SEXP DBconfigSEXP, SEXP levelNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type DBconfig(DBconfigSEXP);
    Rcpp::traits::input_parameter< std::string >::type levelName(levelNameSEXP);
    rcpp_result_gen = Rcpp::wrap(build_sublevelPathes_cpp(DBconfig, levelName));
    return rcpp_result_gen;
END_RCPP
}
// build_allHierarchyPaths_cpp
List build_allHierarchyPaths_cpp(List schema);
RcppExport SEXP _reindeer_build_allHierarchyPaths_cpp(SEXP schemaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type schema(schemaSEXP);
    rcpp_result_gen = Rcpp::wrap(build_allHierarchyPaths_cpp(schema));
    return rcpp_result_gen;
END_RCPP
}
// find_segmentLevels_cpp
StringVector find_segmentLevels_cpp(List DBconfig, std::string attrName);
RcppExport SEXP _reindeer_find_segmentLevels_cpp(SEXP DBconfigSEXP, SEXP attrNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type DBconfig(DBconfigSEXP);
    Rcpp::traits::input_parameter< std::string >::type attrName(attrNameSEXP);
    rcpp_result_gen = Rcpp::wrap(find_segmentLevels_cpp(DBconfig, attrName));
    return rcpp_result_gen;
END_RCPP
}
// get_levelDefinition_cpp
List get_levelDefinition_cpp(List DBconfig, std::string name);
RcppExport SEXP _reindeer_get_levelDefinition_cpp(SEXP DBconfigSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type DBconfig(DBconfigSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(get_levelDefinition_cpp(DBconfig, name));
    return rcpp_result_gen;
END_RCPP
}
// get_hierPathsConnectingLevels_cpp
List get_hierPathsConnectingLevels_cpp(List DBconfig, std::string levelName1, std::string levelName2);
RcppExport SEXP _reindeer_get_hierPathsConnectingLevels_cpp(SEXP DBconfigSEXP, SEXP levelName1SEXP, SEXP levelName2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type DBconfig(DBconfigSEXP);
    Rcpp::traits::input_parameter< std::string >::type levelName1(levelName1SEXP);
    Rcpp::traits::input_parameter< std::string >::type levelName2(levelName2SEXP);
    rcpp_result_gen = Rcpp::wrap(get_hierPathsConnectingLevels_cpp(DBconfig, levelName1, levelName2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_reindeer_get_allAttributeNames_cpp", (DL_FUNC) &_reindeer_get_allAttributeNames_cpp, 1},
    {"_reindeer_get_linkLevelChildrenNames_cpp", (DL_FUNC) &_reindeer_get_linkLevelChildrenNames_cpp, 2},
    {"_reindeer_expand_linkPath_cpp", (DL_FUNC) &_reindeer_expand_linkPath_cpp, 1},
    {"_reindeer_build_sublevelPathes_cpp", (DL_FUNC) &_reindeer_build_sublevelPathes_cpp, 2},
    {"_reindeer_build_allHierarchyPaths_cpp", (DL_FUNC) &_reindeer_build_allHierarchyPaths_cpp, 1},
    {"_reindeer_find_segmentLevels_cpp", (DL_FUNC) &_reindeer_find_segmentLevels_cpp, 2},
    {"_reindeer_get_levelDefinition_cpp", (DL_FUNC) &_reindeer_get_levelDefinition_cpp, 2},
    {"_reindeer_get_hierPathsConnectingLevels_cpp", (DL_FUNC) &_reindeer_get_hierPathsConnectingLevels_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_reindeer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
