# ==============================================================================
# describe() — emit standards-compliant corpus documentation (Item 5)
# ==============================================================================
#
# A single entry point that produces README.md, CMDI XML, and DataCite 4.5
# JSON for a corpus. All three formats consume one shared summary built by
# collect_corpus_summary(); CMDI delegates to the existing
# create_cmdi_metadata() implementation in R/reindeer_cmdi.R.

#' Build a shared, format-agnostic snapshot of a corpus
#'
#' Returns a list with database, participant, level/track, and duration
#' summaries. Used as the input to README, CMDI, and DataCite emitters.
#'
#' @param corpus_obj A reindeer `corpus` object.
#' @param verbose Logical; passed through to underlying collectors.
#' @return A list with named summary fields.
#' @keywords internal
#' @noRd
collect_corpus_summary <- function(corpus_obj, verbose = FALSE) {
  if (!S7::S7_inherits(corpus_obj, corpus)) {
    cli::cli_abort("Input must be a {.cls corpus} object")
  }
  db_handle <- get_handle(corpus_obj)
  db_config <- load_DBconfig(db_handle)

  db <- collect_database_metadata(db_handle, db_config, verbose = verbose)
  participants <- collect_participant_metadata(db_handle, verbose = verbose)

  # Project / funding / team metadata, if present at database level
  proj <- list(name = NULL, description = NULL, funder = NULL,
               grantNumber = NULL, team = list())
  meta_file <- file.path(corpus_obj@basePath, "METADATA.json")
  if (file.exists(meta_file)) {
    db_meta <- tryCatch(
      jsonlite::read_json(meta_file, simplifyVector = TRUE),
      error = function(e) list()
    )
    if (!is.null(db_meta$project)) {
      proj$name <- db_meta$project$name %||% NULL
      proj$description <- db_meta$project$description %||% NULL
      proj$startDate <- db_meta$project$startDate %||% NULL
      proj$website <- db_meta$project$website %||% NULL
    }
    if (!is.null(db_meta$funding)) {
      proj$funder <- db_meta$funding$funder %||% NULL
      proj$grantNumber <- db_meta$funding$grantNumber %||% NULL
    }
    if (!is.null(db_meta$team)) proj$team <- db_meta$team
  }

  list(
    name = db$name,
    uuid = db$uuid,
    base_path = corpus_obj@basePath,
    media_extension = db$media_extension %||% "wav",
    n_sessions = db$n_sessions,
    n_bundles = db$n_bundles,
    n_levels = db$n_levels,
    n_links = db$n_links,
    n_ssff_tracks = db$n_ssff_tracks,
    levels = db$levels,
    links = db$links,
    ssff_tracks = db$ssff_tracks,
    bundle_list = db$bundle_list,
    total_duration_sec = db$total_duration_sec,
    total_duration_hms = db$total_duration_hms,
    participants = participants,
    project = proj
  )
}

#' @keywords internal
.emit_readme <- function(summary, path) {
  lines <- character()
  add <- function(...) lines <<- c(lines, paste0(...))
  add("# ", summary$name)
  add("")
  if (!is.null(summary$project$description) &&
      nzchar(summary$project$description)) {
    add(summary$project$description)
    add("")
  } else {
    add("Speech corpus packaged with the reindeer R package.")
    add("")
  }
  add("## Contents")
  add("")
  add("- Sessions: ", summary$n_sessions)
  add("- Bundles: ", summary$n_bundles)
  add("- Annotation levels: ", summary$n_levels)
  add("- Hierarchy links: ", summary$n_links)
  add("- SSFF signal tracks: ", summary$n_ssff_tracks)
  if (!is.null(summary$total_duration_hms) &&
      nzchar(summary$total_duration_hms)) {
    add("- Total media duration: ", summary$total_duration_hms)
  }
  add("- Media file extension: `", summary$media_extension, "`")
  add("")
  if (length(summary$levels) > 0) {
    add("## Annotation levels")
    add("")
    for (lvl in summary$levels) {
      add("- **", lvl$name, "** (`", lvl$type, "`)")
    }
    add("")
  }
  if (length(summary$ssff_tracks) > 0) {
    add("## Signal tracks")
    add("")
    for (tr in summary$ssff_tracks) {
      add("- ", tr$name, ": `", tr$fileExtension %||% "?", "`")
    }
    add("")
  }
  if (NROW(summary$participants) > 0) {
    n_part <- if (is.data.frame(summary$participants)) {
      nrow(summary$participants)
    } else {
      length(summary$participants)
    }
    add("## Participants")
    add("")
    add("- Total participants with metadata: ", n_part)
    add("")
  }
  if (!is.null(summary$project$funder) &&
      nzchar(summary$project$funder)) {
    add("## Funding")
    add("")
    add("- Funder: ", summary$project$funder)
    if (!is.null(summary$project$grantNumber)) {
      add("- Grant number: ", summary$project$grantNumber)
    }
    add("")
  }
  add("## Citation")
  add("")
  add("Please cite the corpus using its UUID `", summary$uuid, "`.")
  add("")
  add("---")
  add("")
  add("_Generated by reindeer::describe()._")

  writeLines(lines, path, useBytes = TRUE)
  invisible(path)
}

#' @keywords internal
.emit_datacite <- function(summary, path) {
  publication_year <- as.integer(format(Sys.Date(), "%Y"))
  if (!is.null(summary$project$startDate)) {
    yr <- suppressWarnings(as.integer(substr(summary$project$startDate, 1, 4)))
    if (!is.na(yr)) publication_year <- yr
  }

  creators <- list()
  team <- summary$project$team
  if (is.data.frame(team) && nrow(team) > 0) {
    for (i in seq_len(nrow(team))) {
      creators[[length(creators) + 1L]] <- list(
        name = team$name[i],
        affiliation = if (!is.null(team$affiliation)) {
          list(list(name = team$affiliation[i]))
        } else {
          list()
        }
      )
    }
  } else if (is.list(team) && length(team) > 0) {
    for (member in team) {
      creators[[length(creators) + 1L]] <- list(
        name = member$name %||% "Unknown",
        affiliation = if (!is.null(member$affiliation)) {
          list(list(name = member$affiliation))
        } else {
          list()
        }
      )
    }
  } else {
    creators[[1L]] <- list(name = "Unknown")
  }

  doc <- list(
    data = list(
      type = "dois",
      attributes = list(
        identifiers = list(list(
          identifier = summary$uuid,
          identifierType = "UUID"
        )),
        creators = creators,
        titles = list(list(title = summary$name)),
        publisher = summary$project$funder %||% "Unspecified",
        publicationYear = publication_year,
        types = list(
          resourceTypeGeneral = "Audiovisual",
          resourceType = "Speech corpus"
        ),
        descriptions = list(list(
          description = summary$project$description %||%
            "Speech corpus packaged with reindeer.",
          descriptionType = "Abstract"
        )),
        formats = list(paste0("audio/", summary$media_extension)),
        sizes = list(
          paste0(summary$n_bundles, " bundles"),
          paste0(round(summary$total_duration_sec %||% 0, 1), " s")
        )
      )
    )
  )
  jsonlite::write_json(
    doc, path, auto_unbox = TRUE, pretty = TRUE, null = "null"
  )
  invisible(path)
}

#' Emit standards-compliant corpus documentation
#'
#' Produces README, CMDI XML, and DataCite 4.5 JSON for a corpus in one
#' call. All three formats are derived from a single shared summary
#' built by `collect_corpus_summary()`. CMDI delegates to
#' `create_cmdi_metadata()`.
#'
#' Existing files at the target paths are never overwritten unless
#' `force = TRUE`.
#'
#' @param corpus_obj A reindeer `corpus` object.
#' @param output_dir Directory to write outputs into. Defaults to the
#'   corpus base path.
#' @param formats Character vector of formats to emit. Any subset of
#'   `c("readme", "cmdi", "datacite")`.
#' @param profile CMDI profile (`"speech-corpus"`, `"media-corpus"`,
#'   `"speech-corpus-dlu"`).
#' @param force Logical; overwrite existing files.
#' @param verbose Logical; print progress.
#' @return A named character vector of paths written, invisibly.
#'
#' @examplesIf interactive()
#' corp <- corpus("path/to/db_emuDB")
#' describe_corpus(corp)
#' describe_corpus(corp, formats = "readme", force = TRUE)
#'
#' @export
describe_corpus <- function(corpus_obj,
                     output_dir = NULL,
                     formats = c("readme", "cmdi", "datacite"),
                     profile = "speech-corpus",
                     force = FALSE,
                     verbose = TRUE) {
  if (!S7::S7_inherits(corpus_obj, corpus)) {
    cli::cli_abort("Input must be a {.cls corpus} object")
  }
  formats <- match.arg(formats, several.ok = TRUE)
  if (is.null(output_dir)) output_dir <- corpus_obj@basePath
  if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

  # Auto-regenerate: if add_metadata() / create_session_and_bundle() flipped
  # the dirty bit, force a rewrite of the FAIR artifacts to keep them in
  # sync with the underlying METADATA.json files.
  if (.is_metadata_dirty(corpus_obj)) {
    if (verbose) {
      cli::cli_alert_info(
        "Metadata changed since last {.fn describe_corpus} - regenerating artifacts."
      )
    }
    force <- TRUE
  }

  summary <- collect_corpus_summary(corpus_obj, verbose = verbose)

  written <- character()
  if ("readme" %in% formats) {
    target <- file.path(output_dir, "README.md")
    if (file.exists(target) && !force) {
      target <- file.path(output_dir, "README-generated.md")
    }
    .emit_readme(summary, target)
    written <- c(written, readme = target)
    if (verbose) cli::cli_alert_success("Wrote {.path {target}}")
  }
  if ("cmdi" %in% formats) {
    target <- file.path(output_dir, paste0(summary$name, "_cmdi.xml"))
    if (file.exists(target) && !force) {
      target <- file.path(output_dir, paste0(summary$name, "_cmdi-generated.xml"))
    }
    create_cmdi_metadata(corpus_obj, output_file = target,
                         profile = profile, verbose = verbose)
    written <- c(written, cmdi = target)
  }
  if ("datacite" %in% formats) {
    target <- file.path(output_dir, "datacite.json")
    if (file.exists(target) && !force) {
      target <- file.path(output_dir, "datacite-generated.json")
    }
    .emit_datacite(summary, target)
    written <- c(written, datacite = target)
    if (verbose) cli::cli_alert_success("Wrote {.path {target}}")
  }

  # Artifacts are back in sync — clear the dirty bit.
  .clear_metadata_dirty(corpus_obj)

  invisible(written)
}
