# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_allAttributeNames_cpp <- function(levelDefinitions) {
    .Call(`_reindeer_get_allAttributeNames_cpp`, levelDefinitions)
}

get_linkLevelChildrenNames_cpp <- function(linkDefinitions, superlevelName) {
    .Call(`_reindeer_get_linkLevelChildrenNames_cpp`, linkDefinitions, superlevelName)
}

expand_linkPath_cpp <- function(path) {
    .Call(`_reindeer_expand_linkPath_cpp`, path)
}

build_sublevelPathes_cpp <- function(DBconfig, levelName) {
    .Call(`_reindeer_build_sublevelPathes_cpp`, DBconfig, levelName)
}

build_allHierarchyPaths_cpp <- function(schema) {
    .Call(`_reindeer_build_allHierarchyPaths_cpp`, schema)
}

find_segmentLevels_cpp <- function(DBconfig, attrName) {
    .Call(`_reindeer_find_segmentLevels_cpp`, DBconfig, attrName)
}

get_levelDefinition_cpp <- function(DBconfig, name) {
    .Call(`_reindeer_get_levelDefinition_cpp`, DBconfig, name)
}

get_hierPathsConnectingLevels_cpp <- function(DBconfig, levelName1, levelName2) {
    .Call(`_reindeer_get_hierPathsConnectingLevels_cpp`, DBconfig, levelName1, levelName2)
}

